name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: codeberg-medium
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Setup Python
        uses: https://code.forgejo.org/actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tools
        run: pip install build twine

      - name: Build PyPI packages
        run: make build

      - name: Validate packages
        run: make check

      - name: Build .deb packages
        run: |
          VERSION=$(grep '^__version__' eip_search/__init__.py | cut -d'"' -f2)

          # Install fpm
          sudo apt-get update && sudo apt-get install -y --no-install-recommends ruby ruby-dev gcc make
          sudo gem install --no-document fpm

          # Create minimal package root — the postinst script creates the
          # venv on the target using its own Python, so we only ship the
          # version marker.  This avoids Python version and architecture
          # mismatches between CI and the target machine.
          PKG_ROOT=$(mktemp -d)
          mkdir -p "${PKG_ROOT}/opt/eip-search"
          echo "${VERSION}" > "${PKG_ROOT}/opt/eip-search/.package-version"

          # Build .deb for each distro (version suffix ensures unique pool files)
          for DISTRO_TAG in ubuntu-jammy ubuntu-noble ubuntu-plucky debian-bookworm debian-trixie kali-rolling; do
            case "$DISTRO_TAG" in
              ubuntu-jammy)     SUITE=jammy ;;
              ubuntu-noble)     SUITE=noble ;;
              ubuntu-plucky)    SUITE=plucky ;;
              debian-bookworm)  SUITE=bookworm ;;
              debian-trixie)    SUITE=trixie ;;
              kali-rolling)     SUITE=kali-rolling ;;
            esac
            DEB_VERSION="${VERSION}~${SUITE}"
            fpm \
              -s dir \
              -t deb \
              -n eip-search \
              -v "${DEB_VERSION}" \
              -a all \
              --description "CLI intelligence tool for the Exploit Intelligence Platform" \
              --url "https://codeberg.org/exploit-intel/eip-search" \
              --license "MIT" \
              --maintainer "Exploit Intelligence Platform" \
              --vendor "Exploit Intelligence Platform" \
              --category utils \
              --depends python3 \
              --depends python3-venv \
              --deb-no-default-config-files \
              --before-install packaging/deb/preinst.sh \
              --after-install packaging/deb/postinst.sh \
              --after-remove packaging/deb/postrm.sh \
              -p "dist/eip-search_${VERSION}_${DISTRO_TAG}_all.deb" \
              -C "${PKG_ROOT}" \
              opt/eip-search
          done

          rm -rf "${PKG_ROOT}"
          ls -lh dist/*.deb

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: make pypi

      - name: Create Release
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          TAG="${{ github.ref_name }}"
          API_URL="${{ github.server_url }}/api/v1/repos/${{ github.repository }}"

          # Create release
          RELEASE_ID=$(curl -sf -X POST \
            -H "Authorization: token ${RELEASE_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\": \"${TAG}\", \"name\": \"${TAG}\", \"draft\": false, \"prerelease\": false}" \
            "${API_URL}/releases" | jq -r '.id')

          echo "Created release ${TAG} (id: ${RELEASE_ID})"

          # Upload assets
          for file in dist/*.deb dist/*.whl dist/*.tar.gz; do
            [ -f "$file" ] || continue
            echo "Uploading $(basename "$file")..."
            curl -sf -X POST \
              -H "Authorization: token ${RELEASE_TOKEN}" \
              -F "attachment=@${file}" \
              "${API_URL}/releases/${RELEASE_ID}/assets"
          done

      - name: Upload to APT repo
        env:
          REPO_SSH_KEY: ${{ secrets.REPO_SSH_KEY }}
        run: |
          if [ -z "$REPO_SSH_KEY" ]; then
            echo "REPO_SSH_KEY not set, skipping APT repo upload"
            exit 0
          fi

          mkdir -p ~/.ssh
          echo "$REPO_SSH_KEY" > ~/.ssh/repo_key
          chmod 600 ~/.ssh/repo_key
          ssh-keyscan REDACTED >> ~/.ssh/known_hosts 2>/dev/null

          scp -i ~/.ssh/repo_key dist/*.deb root@REDACTED:/var/www/apt/incoming/
          ssh -i ~/.ssh/repo_key root@REDACTED "bash /root/upload-debs.sh"

          rm -f ~/.ssh/repo_key
